### ISSUE TITLE
Ошибка при получении аттрибутов

### ISSUE THREAD

**Issue by happyendik** [isudakoff/yii2-mailru-authclient#1]
Установил расширение через композер. Добавил MailRu клиент к auth-клиентам. 
Получил ошибку.
![2017-07-19 15-03-16](https://user-images.githubusercontent.com/25950192/28366002-7ec43aee-6c93-11e7-989c-84ac1ac2d986.png)

**Comment by alexeevdv** [comment]
HttpClient не может распарсить ответ сервера, т.к. сервер выдает некорректный Content-Type. Должен выдавать application/json. Об этом есть соответствующий [RFC](http://www.ietf.org/rfc/rfc4627.txt), но корпорация зла как всегда клала болт

**Comment by isudakoff** [comment]
@happyendik @alexeevdv  Fixed
